### PR TITLE
Pass delimiter to CSV reading code.

### PR DESCRIPTION
**Pull request by alper**
This way files that do not use commas as a delimiter can also be
read.

### CODE REVIEW

**Comment by alper** [comment]
I may still need to whip up a test that uses this since none of the existing ones do.

**Comment by reubano** [comment]
Thanks for this! And yes, if you can, please add a test to verify that this works.

**Comment by alper** [comment]
A couple errors are being caused by the fact that `payee` is not properly extracted on python2.7. 

The field definition is `'payee': itemgetter('Auftraggeber/Empfänger')` and of course that causes encoding problems. I've poked around a bit here and there but I'm not sure whether I care enough about that old python version to spend hours tracking this down.

I'll take another look later.

**Comment by reubano** [comment]
@alper ok, well thanks for tracking it down to an encoding problem. Don't spend more than 20-30 mins more looking into it. I've dealt enough with py2 encoding errors to look at it later. Let me know if you can't easily figure out exactly what's wrong, and I'll merge it as is.

**Comment by alper** [comment]
This should fix #26

**Pull request merged**
